//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaAmigos
    {
        public int id { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public Nullable<int> idAmigo { get; set; }
    
        public virtual Amigo Amigo { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
