//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursoFoto
    {
        public RecursoFoto()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int id { get; set; }
        public string ruta { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Cuenta> Cuenta { get; set; }
    }
}
